/** Shared city suggestions for birth-place comboboxes (quiz + people). */
export const BIRTH_PLACE_OPTIONS = [
  'New York, USA',
  'Los Angeles, USA',
  'Chicago, USA',
  'Houston, USA',
  'Miami, USA',
  'San Francisco, USA',
  'Seattle, USA',
  'Boston, USA',
  'Washington, D.C., USA',
  'Toronto, Canada',
  'Vancouver, Canada',
  'Montreal, Canada',
  'Mexico City, Mexico',
  'São Paulo, Brazil',
  'Rio de Janeiro, Brazil',
  'Buenos Aires, Argentina',
  'Lima, Peru',
  'Bogotá, Colombia',
  'Santiago, Chile',
  'London, UK',
  'Manchester, UK',
  'Edinburgh, UK',
  'Dublin, Ireland',
  'Paris, France',
  'Lyon, France',
  'Berlin, Germany',
  'Munich, Germany',
  'Hamburg, Germany',
  'Amsterdam, Netherlands',
  'Brussels, Belgium',
  'Zurich, Switzerland',
  'Vienna, Austria',
  'Rome, Italy',
  'Milan, Italy',
  'Madrid, Spain',
  'Barcelona, Spain',
  'Lisbon, Portugal',
  'Stockholm, Sweden',
  'Oslo, Norway',
  'Copenhagen, Denmark',
  'Helsinki, Finland',
  'Warsaw, Poland',
  'Prague, Czech Republic',
  'Budapest, Hungary',
  'Athens, Greece',
  'Istanbul, Turkey',
  'Moscow, Russia',
  'Saint Petersburg, Russia',
  'Kyiv, Ukraine',
  'Bucharest, Romania',
  'Sofia, Bulgaria',
  'Belgrade, Serbia',
  'Dubai, UAE',
  'Abu Dhabi, UAE',
  'Riyadh, Saudi Arabia',
  'Jeddah, Saudi Arabia',
  'Doha, Qatar',
  'Kuwait City, Kuwait',
  'Cairo, Egypt',
  'Casablanca, Morocco',
  'Lagos, Nigeria',
  'Nairobi, Kenya',
  'Johannesburg, South Africa',
  'Cape Town, South Africa',
  'Karachi, Pakistan',
  'Lahore, Pakistan',
  'Islamabad, Pakistan',
  'Rawalpindi, Pakistan',
  'Faisalabad, Pakistan',
  'Peshawar, Pakistan',
  'Multan, Pakistan',
  'Hyderabad, Pakistan',
  'Quetta, Pakistan',
  'Mumbai, India',
  'Delhi, India',
  'Bangalore, India',
  'Hyderabad, India',
  'Chennai, India',
  'Kolkata, India',
  'Dhaka, Bangladesh',
  'Colombo, Sri Lanka',
  'Kathmandu, Nepal',
  'Singapore',
  'Kuala Lumpur, Malaysia',
  'Jakarta, Indonesia',
  'Bangkok, Thailand',
  'Ho Chi Minh City, Vietnam',
  'Manila, Philippines',
  'Hong Kong',
  'Taipei, Taiwan',
  'Shanghai, China',
  'Beijing, China',
  'Guangzhou, China',
  'Tokyo, Japan',
  'Osaka, Japan',
  'Seoul, South Korea',
  'Sydney, Australia',
  'Melbourne, Australia',
  'Brisbane, Australia',
  'Auckland, New Zealand',
  'Tel Aviv, Israel',
  'Tehran, Iran',
] as const
