import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ru: {
    title: 'SoulPlus AI',
    subtitle: 'Откройте свой путь через древнюю мудрость нумерологии',
    enterDate: 'Введите дату рождения',
    calculateMatrix: 'Мы рассчитаем вашу уникальную матрицу судьбы',
    dateLabel: 'Дата рождения',
    dateFormat: 'Формат: ДД/ММ/ГГГГ',
    datePlaceholder: '30/01/1955',
    calculateButton: 'Рассчитать матрицу',
    privacyNote: 'Ваши данные не сохраняются и остаются полностью конфиденциальными',
    yourMatrix: 'Ваша Матрица Судьбы',
    premiumTitle: 'Получите полный отчёт о вашей судьбе',
    premiumDesc: 'Детальные интерпретации, анализ совместимости, руководство по жизненному пути',
    premiumButton: 'Перейти на Premium',
    resetButton: 'Рассчитать другую матрицу',
    successToast: 'Ваша матрица судьбы рассчитана!',
    errorToast: 'Неверная дата. Проверьте введенные данные.',
    compatibilityResult: 'Результат совместимости',
    back: 'Назад',
    positionTop: 'Высший талант',
    positionLeft: 'Таланты/Проявление в мир',
    positionCenter: 'Энергия Пары',
    positionRight: 'Задача души',
    positionBottom: 'Карма',
    love: 'Любовь',
    money: 'Материальное',
    karma: 'Карма',
    personalityDossier: 'Досье вашей личности',
    premiumContent: 'Премиум контент',
    premiumContentDesc: 'Получите доступ к полному анализу совместимости, включая слабые стороны, денежные блоки и детальные рекомендации.',
    getPremiumAccess: 'Получить премиум доступ',
    maybeLater: 'Может быть позже',
    compatibilityMatrixTitle: 'Матрица Совместимости',
    compatibilitySubtitle: 'Откройте динамику отношений между двумя людьми',
    backToPersonalMatrix: 'Назад к Личной Матрице',
    enterTwoBirthDates: 'Введите Две Даты Рождения',
    calculateCompatibilityDesc: 'Рассчитайте совместимость между двумя людьми',
    personA: 'Персона А',
    personB: 'Персона Б',
    name: 'Имя',
    enterName: 'Введите имя',
    gender: 'Пол',
    male: 'Мужчина',
    female: 'Женщина',
    dateOfBirth: 'Дата рождения',
    calculateCompatibilityButton: 'Рассчитать Совместимость',
    compatibilityAnalysis: 'Анализ Совместимости',
    individualMatrices: 'Индивидуальные Матрицы',
    compatibilityMatrix: 'Матрица Совместимости',
    combinedEnergies: 'Объединенные энергии партнерства',
    compatibilityCalculated: 'Совместимость успешно рассчитана!',
    invalidDateFormat: 'Пожалуйста, введите корректные даты в формате ДД/ММ/ГГГГ',
    compatibilityPremiumTitle: 'Полный Отчет о Совместимости',
    compatibilityPremiumDesc: 'Получите детальную информацию, персональные рекомендации и советы по отношениям',
    compatibilityPremiumButton: 'Перейти на Премиум',
    pairCenter: 'Центр Пары',
    pairCenterDesc: 'Основная энергия отношений',
    loveCompatibility: 'Любовная Совместимость',
    loveCompatibilityDesc: 'Романтическая и эмоциональная связь',
    challengeArea: 'Зона Вызовов',
    challengeAreaDesc: 'Области, требующие внимания и роста',
    harmonyZone: 'Зона Гармонии',
    harmonyZoneDesc: 'Естественные области согласия и потока',
    growthPotential: 'Потенциал Роста',
    growthPotentialDesc: 'Возможности для взаимного развития',
    communication: 'Коммуникация',
    communicationDesc: 'Как вы общаетесь и понимаете друг друга',
    newCompatibilityAnalysis: 'Новый Анализ Совместимости',
    compatibilityHigh: 'Высокая',
    compatibilityMedium: 'Средняя',
    compatibilityChallenging: 'Требует усилий',
    compatibilityUnknown: 'Неизвестно',
    compatibilityExcellent: 'Отличная совместимость',
    compatibilityGood: 'Хорошая совместимость с некоторыми трудностями',
    compatibilityRequires: 'Требует понимания и компромиссов',
    healthChart: 'Карта Здоровья',
    chakra: 'Чакра',
    physiology: 'Физиология',
    energy: 'Энергия',
    balance: 'Баланс',
    summary: 'Итог',
    totalEnergyField: 'Общее энергополе',
    navHome: 'Главная',
    navCalculator: 'Калькулятор',
    navRates: 'Тарифы',
    navBlog: 'Блог',
    navAbout: 'О сервисе',
    navContact: 'Контакты',
    navLogin: 'Войти',
    navSignup: 'Регистрация',
    navMyAvatar: 'Мой Аватар',
    navReading: 'Моё чтение',
    navDiary: 'Дневник',
    navShop: 'Магазин',
    navNotes: 'Мои Заметки',
    navTip: 'Совет дня',
    navLogout: 'Выйти',
    navProfile: 'Профиль',
    navCalculatorPage: 'Калькулятор',
    generateAnalysis: 'Генерировать анализ',
    // Avatar Page Tabs
    tabForMe: 'Для меня',
    tabOthers: 'Другие люди',
    tabCompatibility: 'Совместимость',
    tabMessage: 'Послание дня',
    // Rates Page
    ratesTitle: 'Тарифы',
    ratesIntro1: 'Зарегистрировавшись в нашем сервисе, вы получите доступ к множеству бесплатной и полезной информации, которая поможет вам лучше понять себя и составить план улучшения вашей жизни.',
    ratesIntro2: 'Для вашего удобства есть возможность приобрести дополнительные расшифровки матриц ваших членов семьи, друзей или клиентов. Она будет навсегда добавлена в ваш личный кабинет и оплачивается только один раз. Доступность текстов во всех матрицах вашего профиля зависит от выбранного вами тарифа.',
    ratesIntro3: 'Покупая платный тариф, вы получаете подписку на 3 месяца с доступом к дополнительной информации в соответствии с выбранным вами тарифом.',
    ratesIntro4: 'Если у вас есть вопросы по тарифным планам, пожалуйста, ознакомьтесь с нашей',
    ratesFAQ: 'FAQ',
    ratesPage: 'страницей',
    availablePlans: 'Доступные планы',
    thisPlanIncludes: 'Этот план включает:',
    mostPopular: 'Самый популярный',
    purchase: 'Купить',
    monthly: 'ежемесячно',
    every3Months: 'каждые 3 месяца',
    faqTitle: 'Часто задаваемые вопросы',
    faqSubtitle: 'Найдите ответы на распространенные вопросы о наших тарифных планах',
    faqQuestion1: 'Что произойдет через 7 дней?',
    faqAnswer1: 'Через 7 дней ваш план автоматически продлится за $6.99/месяц. Вы можете отменить в любое время до этого — без лишних вопросов.',
    faqQuestion2: 'Могу ли я отменить подписку в любое время?',
    faqAnswer2: 'Да, вы можете отменить в любое время в настройках аккаунта или по электронной почте. Никаких штрафов и скрытых платежей.',
    faqQuestion3: 'Что если чтение кажется неточным?',
    faqAnswer3: 'Мы предлагаем 30-дневную гарантию возврата денег. Если чтение вам не подходит, напишите нам — мы вернем полную сумму.',
    faqQuestion4: 'Мои данные в безопасности?',
    faqAnswer4: 'Абсолютно. Ваши данные зашифрованы, никогда не передаются и не продаются. Ваши ответы используются только для создания чтения.',
    faqQuestion5: 'Есть ли гарантия возврата денег?',
    faqAnswer5: 'Да, мы предлагаем 30-дневную гарантию возврата денег, если вы не удовлетворены.',
    planBasic: 'Базовый',
    planSlim: 'Выгодный',
    planFull: 'Полный',
    sub1Month: 'ПОДПИСКА НА 1 МЕСЯЦ',
    sub3Months: 'ПОДПИСКА НА 3 МЕСЯЦА',
    featureProfile: 'Работает для вашей матрицы в профиле',
    featureAddMatrix: 'Работает для дополнительных купленных матриц в профиле',
    featureCompMatrix: 'Работает для купленных матриц совместимости в профиле',
    featureEnergies: 'Доступ ко всем описаниям энергий',
    featureDiary: 'Доступ к интерактивному дневнику',
    featureGraphs: 'Доступ ко всем аналитическим графикам',
    featureMotd: 'Доступ к дополнительным разделам послания дня - любовь и отношения, деньги и карьера',
    featureNotes: 'Доступ к заметкам',
    featureAllCalc: 'Применимо к расчетам ВСЕХ матриц',
    featureNoLimit: 'Расшифровка всех энергий всех матриц без ограничений',
    featureCompNoLimit: 'Расшифровка всех энергий матриц совместимости без ограничений',
    featureAllSections: 'Доступ ко всем дополнительным разделам аватариума',
    giftFreeMatrix: 'После покупки получите бесплатно +1 матрицу',
    giftFreeCompMatrix: 'После покупки получите бесплатно +1 матрицу совместимости',
    giftRenewalMatrix: 'При каждом продлении бесплатно +1 матрица',
    footerNote1: 'С вас будет списано $0.99 сегодня за 7 дней полного доступа. После 7 дней подписка автоматически продлевается за $6.99/месяц до отмены.',
    footerNote2: 'Отменить подписку можно в любое время в настройках аккаунта.',
    navAdmin: 'Панель админа',
    // Calculator Features
    featureIdentity: 'Ваша Личность',
    featureIdentityDesc: 'Раскройте свое истинное «я» и скрытый потенциал.',
    featurePurpose: 'Предназначение',
    featurePurposeDesc: 'Откройте свою миссию и кармический путь.',
    featureDestiny: 'Будущая Судьба',
    featureDestinyDesc: 'Прогнозы для финансов, любви и здоровья.',
    // How It Works
    howItWorks: 'Как это работает',
    stepEnterDate: 'Введите дату',
    stepEnterDateDesc: 'Введите дату своего рождения.',
    stepCalculate: 'Рассчитать',
    stepCalculateDesc: 'Постройте карту своих энергий.',
    stepReveal: 'Раскрыть',
    stepRevealDesc: 'Получите мгновенные озарения.',
  },
  en: {
    title: 'SoulPlus AI',
    subtitle: 'Discover your path through ancient numerology wisdom',
    enterDate: 'Enter your birth date',
    calculateMatrix: 'We will calculate your unique destiny matrix',
    dateLabel: 'Birth date',
    dateFormat: 'Format: DD/MM/YYYY',
    datePlaceholder: '30/01/1955',
    calculateButton: 'Calculate Matrix',
    privacyNote: 'Your data is not stored and remains completely confidential',
    yourMatrix: 'Your Destiny Matrix',
    premiumTitle: 'Get your full destiny report',
    premiumDesc: 'Detailed interpretations, compatibility analysis, life path guidance',
    premiumButton: 'Go Premium',
    resetButton: 'Calculate another matrix',
    successToast: 'Your destiny matrix has been calculated!',
    errorToast: 'Invalid date. Please check your input.',
    compatibilityResult: 'Compatibility Result',
    back: 'Back',
    positionTop: 'Top',
    positionLeft: 'Left',
    positionCenter: 'Core of Union',
    positionRight: 'Right',
    positionBottom: 'Bottom',
    love: 'Love',
    money: 'Money',
    karma: 'Karma',
    personalityDossier: 'Dossier of Your Personality',
    premiumContent: 'Premium Content',
    premiumContentDesc: 'Get access to full compatibility analysis, including weaknesses, money blocks, and detailed recommendations.',
    getPremiumAccess: 'Get Premium Access',
    maybeLater: 'Maybe Later',
    compatibilityMatrixTitle: 'Compatibility Matrix',
    compatibilitySubtitle: 'Discover the dynamics between two people',
    backToPersonalMatrix: 'Back to Personal Matrix',
    enterTwoBirthDates: 'Enter Two Birth Dates',
    calculateCompatibilityDesc: 'Calculate compatibility between two people',
    personA: 'Person A',
    personB: 'Person B',
    name: 'Name',
    enterName: 'Enter name',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    dateOfBirth: 'Date of Birth',
    calculateCompatibilityButton: 'Calculate Compatibility',
    compatibilityAnalysis: 'Compatibility Analysis',
    individualMatrices: 'Individual Matrices',
    compatibilityMatrix: 'Compatibility Matrix',
    combinedEnergies: 'Combined energies of partnership',
    compatibilityCalculated: 'Compatibility calculated successfully!',
    invalidDateFormat: 'Please enter valid dates in DD/MM/YYYY format',
    compatibilityPremiumTitle: 'Unlock Full Compatibility Report',
    compatibilityPremiumDesc: 'Get detailed insights, personalized guidance, and relationship recommendations',
    compatibilityPremiumButton: 'Upgrade to Premium',
    pairCenter: 'Pair Center',
    pairCenterDesc: 'Core energy of the relationship',
    loveCompatibility: 'Love Compatibility',
    loveCompatibilityDesc: 'Romantic and emotional connection',
    challengeArea: 'Challenge Area',
    challengeAreaDesc: 'Areas requiring attention and growth',
    harmonyZone: 'Harmony Zone',
    harmonyZoneDesc: 'Natural areas of agreement and flow',
    growthPotential: 'Growth Potential',
    growthPotentialDesc: 'Opportunities for mutual development',
    communication: 'Communication',
    communicationDesc: 'How you connect and understand each other',
    newCompatibilityAnalysis: 'New Compatibility Analysis',
    compatibilityHigh: 'High',
    compatibilityMedium: 'Medium',
    compatibilityChallenging: 'Challenging',
    compatibilityUnknown: 'Unknown',
    compatibilityExcellent: 'Excellent compatibility',
    compatibilityGood: 'Good compatibility with some challenges',
    compatibilityRequires: 'Requires understanding and compromise',
    healthChart: 'Health Chart',
    chakra: 'Chakra',
    physiology: 'Physiology',
    energy: 'Energy',
    balance: 'Balance',
    summary: 'Summary',
    totalEnergyField: 'Total Energy Field',
    navHome: 'Home',
    navCalculator: 'Calculator',
    navRates: 'Rates',
    navBlog: 'Blog',
    navAbout: 'About',
    navContact: 'Contact us',
    navLogin: 'Log in',
    navSignup: 'Sign up',
    navMyAvatar: 'My Avatar',
    navReading: 'My Reading',
    navDiary: 'Diary',
    navShop: 'Shop',
    navNotes: 'My Notes',
    navTip: 'Tip of the Day',
    navLogout: 'Logout',
    navProfile: 'Profile',
    navCalculatorPage: 'Calculator',
    generateAnalysis: 'Generate Analysis',
    // Avatar Page Tabs
    tabForMe: 'For Me',
    tabOthers: 'Other People',
    tabCompatibility: 'Compatibility',
    tabMessage: 'Message of the Day',
    // Rates Page
    ratesTitle: 'Rates',
    ratesIntro1: 'By signing up for our service you will have access to a wealth of free and useful information to help you better understand yourself and develop a plan to improve your life.',
    ratesIntro2: 'For your convenience, there is an option to purchase additional matrix transcripts of your family members, friends or clients. It will be permanently added to your personal account and is only paid for once. The availability of texts within all matrices of your profile depends on the rate you choose.',
    ratesIntro3: 'Buying a paid tariff, you get a subscription for 3 months with access to more information according to the tariff you have chosen.',
    ratesIntro4: 'If you have any questions regarding the subscription plans, please check our',
    ratesFAQ: 'FAQ',
    ratesPage: 'page',
    availablePlans: 'Available plans',
    thisPlanIncludes: 'This plan includes:',
    mostPopular: 'Most Popular',
    purchase: 'Purchase',
    monthly: 'monthly',
    every3Months: 'every 3 months',
    faqTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Find answers to common questions about our subscription plans',
    faqQuestion1: 'What happens after 7 days?',
    faqAnswer1: 'After 7 days, your plan auto-renews at $6.99/month. You can cancel anytime before that — no questions asked.',
    faqQuestion2: 'Can I cancel anytime?',
    faqAnswer2: 'Yes, you can cancel anytime from your account settings or by emailing us. No penalties, no hidden fees.',
    faqQuestion3: "What if the reading doesn't feel accurate?",
    faqAnswer3: "We offer a 30-day money-back guarantee. If your reading doesn't feel right, email us and we'll refund you in full.",
    faqQuestion4: 'Is my data private?',
    faqAnswer4: 'Absolutely. Your data is encrypted, never shared, and never sold. Your answers are used only to generate your reading.',
    faqQuestion5: 'Is there a money-back guarantee?',
    faqAnswer5: 'Yes, we offer a 30-day money-back guarantee if you\'re not satisfied.',
    planBasic: 'Basic',
    planSlim: 'Slim',
    planFull: 'Full',
    sub1Month: '1-MONTH SUBSCRIPTION',
    sub3Months: '3-MONTH SUBSCRIPTION',
    featureProfile: 'Works for your matrix within your profile',
    featureAddMatrix: 'Works for additional purchased matrixes within your profile',
    featureCompMatrix: 'Works for purchased compatibility matrixes within your profile',
    featureEnergies: 'Access to all energy descriptions',
    featureDiary: 'Access to interactive dairy',
    featureGraphs: 'Access to all analytical graphs',
    featureMotd: 'Access to additional sections of the message of the day - love and relationships, money and career',
    featureNotes: 'Access to notes',
    featureAllCalc: 'Applies to calculations of ALL matrices',
    featureNoLimit: 'Decoding of all energies of all matrices without restrictions',
    featureCompNoLimit: 'Decoding of all energies of compatibility matrices without restrictions',
    featureAllSections: 'Access to all additional sections of the avatarium',
    giftFreeMatrix: 'After purchase get free +1 matrix',
    giftFreeCompMatrix: 'After purchase get free +1 matrix of compatibility',
    giftRenewalMatrix: 'Each renewal get free +1 matrix',
    footerNote1: 'You\'ll be charged $0.99 today for 7 days of full access. After 7 days, auto-renews at $6.99/month until cancelled.',
    footerNote2: 'Cancel any time from your account settings.',
    navAdmin: 'Admin Dashboard',
    // Calculator Features
    featureIdentity: 'Your Identity',
    featureIdentityDesc: 'Uncover your true self and hidden potential.',
    featurePurpose: 'Life Purpose',
    featurePurposeDesc: 'Discover your mission and karmic path.',
    featureDestiny: 'Future Destiny',
    featureDestinyDesc: 'Forecasts for finance, love, and health.',
    // How It Works
    howItWorks: 'How It Works',
    stepEnterDate: 'Enter Date',
    stepEnterDateDesc: 'Input your birth date.',
    stepCalculate: 'Calculate',
    stepCalculateDesc: 'Map your energies.',
    stepReveal: 'Reveal',
    stepRevealDesc: 'Get instant insights.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ru] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
